# --8<-- [start:config]
config:
  init:
    name: Delft model
    # What version of Calliope this model is intended for
    calliope_version: 0.7.0
    broadcast_input_data: true  # allow single indexed parameter data entries to be broadcast across all index items, if there are multiple entries.
    mode: base # Choices: base, operate, spores

  build:
    ensure_feasibility: true # Switching on unmet demand

  solve:
    solver: gurobi
    solver_options:
      Threads: 0  # Use all available CPU cores
# --8<-- [end:config]

# --8<-- [start:parameter_data_definitions]
data_definitions:
  objective_cost_weights:
    data: 1
    index: monetary
    dims: costs
  cost_interest_rate:
    data: 1
    index: monetary
    dims: costs
  # `bigM` sets the scale of unmet demand, which cannot be too high, otherwise the optimisation will not converge
  bigM: 1
# --8<-- [end:parameter_data_definitions]

techs:
  supply_LV_electricity:
    name: Low-voltage electricity supply
    color: '#C5ABE3'
    base_tech: supply
    carrier_out: electricity
    cost_flow_cap:
      data: 1000
      index: monetary
      dims: costs
    flow_cap_max: 200000
    lifetime: 20

  supply_geothermal:
    name: Geothermal heat supply
    color: '#C98AAD'
    base_tech: supply
    carrier_out: HQ_heat
    flow_cap_max: 100000
    cost_flow_cap:
      data: 1000
      index: monetary
      dims: costs
    lifetime: 20

  heat_pump:
    name: Air-to-air heat pump
    color: '#8E2999'
    base_tech: conversion
    carrier_in: electricity
    carrier_out: LQ_heat
    cost_flow_cap:
      data: 5
      index: [[monetary, LQ_heat]]
      dims: [costs, carriers]
    flow_cap_max:
      data: 100000
      index: LQ_heat
      dims: carriers
    flow_out_eff: 4.0
    lifetime: 20

  heat_substation:
    name: HQ to LQ heat conversion substation
    color: '#8E2999'
    base_tech: conversion
    carrier_in: HQ_heat
    carrier_out: LQ_heat
    cost_flow_cap:
      data: 5
      index: [[monetary, LQ_heat]]
      dims: [costs, carriers]
    flow_cap_max:
      data: 100000
      index: LQ_heat
      dims: carriers
    flow_out_eff: 0.9
    lifetime: 20

  demand_electricity:
    name: Electrical demand
    color: '#072486'
    base_tech: demand
    carrier_in: electricity

  demand_LQ_heat:
    name: Heat demand
    color: '#660507'
    base_tech: demand
    carrier_in: LQ_heat

  heat_main:
    name: Substitute for demand to make transmission nodes work
    color: '#660507'
    base_tech: demand
    carrier_in: HQ_heat

# --8<-- [start:data-tables]


data_tables:
  links_costs:
    data: ./links_costs.csv
    rows: techs
    columns: parameters
    add_dims:
      costs: monetary
  links_electricity:
    data: ./links_electricity.csv
    rows: techs
    columns: parameters
    add_dims:
      carriers: electricity
  links_HQ_heat:
    data: ./warmtenet_links_carriers.csv
    rows: techs
    columns: parameters
    add_dims:
      carriers: HQ_heat
  links_LQ_heat:
    data: ./links_LQ_heat.csv
    rows: techs
    columns: parameters
    add_dims:
      carriers: LQ_heat
  links:
    data: ./links_techs.csv
    rows: techs
    columns: parameters
  nodes:
    data: ./nodes_techs.csv
    rows: [nodes, techs, parameters]
    columns: timesteps
  nodes_coordinates:
    data: ./nodes_coordinates.csv
    rows: nodes
    columns: parameters
nodes:
  substation_multatulibuurt:
    techs:
      heat_substation: {}
